# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

logging:
  level:
    ROOT: INFO
    com.zensar.api: INFO
spring:
  profiles:
    active: prod
server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    min-response-size: 1024

application:
  app-backend: "https://jl-nonprod-syst.apigee.net"